### PR TITLE
Continuation of #38.

### LINKED ISSUE #36: Issues with new coverage summary
I'm trying to adapt to the [change of `coverage_summary`](https://github.com/JuliaCI/LocalCoverage.jl/issues/18) in `LocalCoverage v0.4`. I've managed to replace my use of `coverage_summary` with `show(eval_coverage_metrics(...))`:

https://github.com/JuliaQuantumControl/QuantumControlBase.jl/pull/33/files

However, I'm not very happy with the new table format. With version 0.3 I would get something like this:

```
┌────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┬──────────┐
│ File name                                                                                              │ Lines hit │ Coverage │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────┼──────────┤
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/QuantumPropagators.jl │   0 /   0 │        - │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/arnoldi.jl            │  56 /  58 │      97% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/cheby.jl              │  70 / 108 │      65% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/cheby_propagator.jl   │  51 /  95 │      54% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/controls.jl           │  65 / 117 │      56% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/exp_propagator.jl     │  36 /  42 │      86% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/expprop.jl            │   6 /   8 │      75% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/newton.jl             │ 132 / 146 │      90% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/newton_propagator.jl  │  29 /  34 │      85% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/propagate.jl          │  37 /  44 │      84% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/propagator.jl         │  38 /  90 │      42% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/pwc_utils.jl          │  20 /  42 │      48% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/specrad.jl            │  69 /  71 │      97% │
│ /Users/goerz/Documents/Programming/JuliaQuantumControl/QuantumPropagators.jl/src/storage.jl            │  14 /  31 │      45% │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────┼──────────┤
│ TOTAL                                                                                                  │ 623 / 886 │      70% │
└────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────┴──────────┘
```

which is OK, except for that `File name` might be better as a (shorter) relative file name

With version 0.4, I get something like this:

```
┌────────────────────────────────┬─────────────┬──────────┬─────────────────────────────────────┐
│ File name                      │   Lines hit │ Coverage │                             Missing │
├────────────────────────────────┼─────────────┼──────────┼─────────────────────────────────────┤
│ /Users/goerz/Documents/Program │     0 /   0 │        - │                                     │
│ ming/JuliaQuantumControl/Quant │             │          │                                     │
│ umPropagators.jl/src/QuantumPr │             │          │                                     │
│ opagators.jl                   │             │          │                                     │
│ /Users/goerz/Documents/Program │    56 /  58 │      97% │                             85 - 86 │
│ ming/JuliaQuantumControl/Quant │             │          │                                     │
│ umPropagators.jl/src/arnoldi.j │             │          │                                     │
│ l                              │             │          │                                     │
│ /Users/goerz/Documents/Program │    70 / 108 │      65% │     138, 144, 174 - 175, 200, 202 - │
│ ming/JuliaQuantumControl/Quant │             │          │     203, 205 - 208, 210 - 212, 214, │
│ umPropagators.jl/src/cheby.jl  │             │          │    216 - 221, 223 - 224, 226 - 227, │
│                                │             │          │      229, 231, 233 - 238, 240, 242, │
│                                │             │          │                       244, 246, 248 │
│ /Users/goerz/Documents/Program │    51 /  95 │      54% │      25, 104 - 107, 122, 131 - 132, │
│ ming/JuliaQuantumControl/Quant │             │          │     158, 219, 225, 227 - 229, 235 - │
│ umPropagators.jl/src/cheby_pro │             │          │    239, 243 - 244, 246 - 254, 260 - │
│ pagator.jl                     │             │          │       267, 269 - 271, 321, 335, 342 │
│ /Users/goerz/Documents/Program │    90 / 117 │      77% │  65, 151, 161, 191, 228 - 229, 238, │
│ ming/JuliaQuantumControl/Quant │             │          │     259 - 260, 269, 294 - 300, 302, │
│ umPropagators.jl/src/controls. │             │          │    304 - 305, 309 - 310, 334 - 335, │
│ jl                             │             │          │                       371, 377, 384 │
│ /Users/goerz/Documents/Program │    37 /  42 │      88% │                   23, 85, 143 - 145 │
│ ming/JuliaQuantumControl/Quant │             │          │                                     │
│ umPropagators.jl/src/exp_propa │             │          │                                     │
│ gator.jl                       │             │          │                                     │
│ /Users/goerz/Documents/Program │     6 /   8 │      75% │                             55 - 56 │
│ ming/JuliaQuantumControl/Quant │             │          │                                     │
│ umPropagators.jl/src/expprop.j │             │          │                                     │
│ l                              │             │          │                                     │
│ /Users/goerz/Documents/Program │   132 / 146 │      90% │  36, 39 - 41, 103 - 104, 185 - 186, │
│ ming/JuliaQuantumControl/Quant │             │          │           282, 285 - 286, 307 - 309 │
│ umPropagators.jl/src/newton.jl │             │          │                                     │
│ /Users/goerz/Documents/Program │    29 /  34 │      85% │               23, 80 - 81, 114, 130 │
│ ming/JuliaQuantumControl/Quant │             │          │                                     │
│ umPropagators.jl/src/newton_pr │             │          │                                     │
│ opagator.jl                    │             │          │                                     │
│ /Users/goerz/Documents/Program │    40 /  44 │      91% │                    12, 21, 191, 211 │
│ ming/JuliaQuantumControl/Quant │             │          │                                     │
│ umPropagators.jl/src/propagate │             │          │                                     │
│ .jl                            │             │          │                                     │
│ /Users/goerz/Documents/Program │    40 /  90 │      44% │   83, 88 - 89, 99 - 100, 104 - 107, │
│ ming/JuliaQuantumControl/Quant │             │          │     110 - 111, 113, 115, 119 - 122, │
│ umPropagators.jl/src/propagato │             │          │     124, 207, 211 - 212, 216 - 217, │
│ r.jl                           │             │          │     225 - 226, 253, 289 - 290, 292, │
│                                │             │          │     313, 334 - 337, 339, 394 - 397, │
│                                │             │          │     399, 418 - 421, 423 - 425, 427, │
│                                │             │          │                           430 - 431 │
│ /Users/goerz/Documents/Program │    20 /  42 │      48% │   34 - 40, 46 - 49, 51 - 53, 55, 58 │
│ ming/JuliaQuantumControl/Quant │             │          │                       - 60, 78 - 81 │
│ umPropagators.jl/src/pwc_utils │             │          │                                     │
│ .jl                            │             │          │                                     │
│ /Users/goerz/Documents/Program │    69 /  71 │      97% │                             44, 133 │
│ ming/JuliaQuantumControl/Quant │             │          │                                     │
│ umPropagators.jl/src/specrad.j │             │          │                                     │
│ l                              │             │          │                                     │
│ /Users/goerz/Documents/Program │    18 /  31 │      58% │     44, 69 - 73, 75, 98 - 99, 131 - │
│ ming/JuliaQuantumControl/Quant │             │          │                      132, 149 - 150 │
│ umPropagators.jl/src/storage.j │             │          │                                     │
│ l                              │             │          │                                     │
├────────────────────────────────┼─────────────┼──────────┼─────────────────────────────────────┤
│ TOTAL                          │   658 / 886 │      74% │                                     │
└────────────────────────────────┴─────────────┴──────────┴─────────────────────────────────────┘
```

This is far less readable. I don't think I need quite that level of detail on the missing lines in a summary table. I do very much like to know *how many* missing lines there are. I think my ideal output would look like this:

```
┌───────────────────────────┬───────────┬──────────┬─────────┐
│ File name                 │ Lines hit │ Coverage │ Missing │
├───────────────────────────┼───────────┼──────────┼─────────┤
│ src/QuantumPropagators.jl │   0 /   0 │        - │       - │
│ src/arnoldi.jl            │  56 /  58 │      97% │       2 │
│ src/cheby.jl              │  70 / 108 │      65% │      38 │
│ src/cheby_propagator.jl   │  51 /  95 │      54% │      44 │
│ src/controls.jl           │  65 / 117 │      56% │      52 │
│ src/exp_propagator.jl     │  36 /  42 │      86% │       8 │
│ src/expprop.jl            │   6 /   8 │      75% │       2 │
│ src/newton.jl             │ 132 / 146 │      90% │      14 │
│ src/newton_propagator.jl  │  29 /  34 │      85% │       5 │
│ src/propagate.jl          │  37 /  44 │      84% │       7 │
│ src/propagator.jl         │  38 /  90 │      42% │      52 │
│ src/pwc_utils.jl          │  20 /  42 │      48% │      22 │
│ src/specrad.jl            │  69 /  71 │      97% │       2 │
│ src/storage.jl            │  14 /  31 │      45% │      17 │
├───────────────────────────┼───────────┼──────────┼─────────┤
│ TOTAL                     │ 623 / 886 │      70% │     263 │
└───────────────────────────┴───────────┴──────────┴─────────┘
```

There should only be one line per file in this format. It might be nice to have an alternative `show` function that takes some keyword parameters, like `show_missing_lines` to switch between a count of missing lines to a detailed listing of all the missing line numbers, as in the current 0.4 output (then maybe with line breaks, but I'd only start breaking lines if the table would be more than 240 characters wide)

### LINKED ISSUE #40: use a dummy package for testing
While using the package itself for testing may have looked like a clever idea when I wrote the package, it has some drawbacks (namely, preventing infinite recursion requires tricks, and gives 0% coverage).

It would be better to make a tiny package with say, 2 files that have some trivial function, and use that for testing.

### PR DESCRIPTION
**Pull request by tpapp**
Fixes #36 (hopefully).

Also closes #40, including that here because it uncovered a bug that was fixed here (no gaps = reducing over empty collections).

### CODE REVIEW

**Comment by tpapp** [comment]
@goerz: I did some refactoring and now the outputs look like this:

Without gaps (the default):
```julia
Coverage of /home/tamas/code/julia/LocalCoverage/
┌──────────────────────┬───────┬───────┬───────┬───────┐
│ Filename             │ Lines │   Hit │  Miss │     % │
├──────────────────────┼───────┼───────┼───────┼───────┤
│ src/LocalCoverage.jl │   101 │     0 │   101 │    0% │
├──────────────────────┼───────┼───────┼───────┼───────┤
│ TOTAL                │   101 │     0 │   101 │    0% │
└──────────────────────┴───────┴───────┴───────┴───────┘
```
And with gaps:
```julia
Coverage of /home/tamas/code/julia/LocalCoverage/
┌──────────────────────┬───────┬───────┬───────┬───────┬─────────────────────────────────────┐
│ Filename             │ Lines │   Hit │  Miss │     % │ Gaps                                │
├──────────────────────┼───────┼───────┼───────┼───────┼─────────────────────────────────────┤
│ src/LocalCoverage.jl │   101 │     0 │   101 │    0% │ 29, 31, 74–76, 78, 82, 84, 86–89,   │
│                      │       │       │       │       │ 97–105, 107–115, 117, 119,          │
│                      │       │       │       │       │ 123–124, 127, 149–155, 157,         │
│                      │       │       │       │       │ 160–162, 174–181, 183–185,          │
│                      │       │       │       │       │ 205–207, 209–216, 228–231, 233,     │
│                      │       │       │       │       │ 246–249, 251, 254–255, 257–258,     │
│                      │       │       │       │       │ 260, 266–267, 269, 272–273,         │
│                      │       │       │       │       │ 289–294, 297–300, 311–312, 314      │
├──────────────────────┼───────┼───────┼───────┼───────┼─────────────────────────────────────┤
│ TOTAL                │   101 │     0 │   101 │    0% │                                     │
└──────────────────────┴───────┴───────┴───────┴───────┴─────────────────────────────────────┘
```

Does this fix things for you? Any other suggestions?

**Comment by tpapp** [comment]
@gabriel-ss, @goerz, a review would be appreciated.

**Comment by tpapp** [comment]
This is what output looks like after the tweaks:
```julia
Coverage of /home/tamas/code/julia/LocalCoverage/test/DummyPackage/
┌─────────────────────┬───────┬─────┬──────┬──────┐
│ Filename            │ Lines │ Hit │ Miss │    % │
├─────────────────────┼───────┼─────┼──────┼──────┤
│ src/DummyPackage.jl │     1 │   1 │    0 │ 100% │
│ src/bar.jl          │     2 │   1 │    1 │  50% │
├─────────────────────┼───────┼─────┼──────┼──────┤
│ TOTAL               │     3 │   2 │    1 │  67% │
└─────────────────────┴───────┴─────┴──────┴──────┘
Coverage of /home/tamas/code/julia/LocalCoverage/test/DummyPackage/
┌─────────────────────┬───────┬─────┬──────┬──────┬─────────────────────────────────────────────────────────┐
│ Filename            │ Lines │ Hit │ Miss │    % │ Gaps                                                    │
├─────────────────────┼───────┼─────┼──────┼──────┼─────────────────────────────────────────────────────────┤
│ src/DummyPackage.jl │     1 │   1 │    0 │ 100% │                                                         │
│ src/bar.jl          │     2 │   1 │    1 │  50% │ 3                                                       │
├─────────────────────┼───────┼─────┼──────┼──────┼─────────────────────────────────────────────────────────┤
│ TOTAL               │     3 │   2 │    1 │  67% │                                                         │
└─────────────────────┴───────┴─────┴──────┴──────┴─────────────────────────────────────────────────────────┘
```

**Comment by gabriel-ss** [comment]
Looks good to me, tested on my system and everything works fine, except that line 298:
```julia
    was_target_met = coverage.coverage >= target_coverage
```
should be:
```julia
    was_target_met = coverage.coverage_percentage >= target_coverage
```

I would also suggest a small change for the sake of convenience:
```julia
function report_coverage(pkg = nothing; target_coverage = 80, print_gaps = false)
    coverage = generate_coverage(pkg)
    show(IOContext(stdout, :print_gaps => print_gaps), coverage)
    report_coverage(coverage, target_coverage)
end
```
Apart from that, the changes look pretty good!

On a side note, I think `rm(COVDIR, LCOVINFO)` should be `rm(joinpath(COVDIR, LCOVINFO))` in line 241.

**Comment by tpapp** [comment]
@gabriel-ss: thanks, I unified the interface and renamed the function.

**Pull request merged**
