### PR TITLE
Jwscook/pkgdirdeprecation

### PR DESCRIPTION
**Pull request by jwscook**
I was getting the following deprecation warning:

```julia
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import JuliaExample; joinpath(dirname(pathof(JuliaExample)), "..", paths...)`.
└ @ Pkg /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Pkg.jl:566
```

This is a PR to fix the deprecation warning, but the path handling is now a bit ugly.

### CODE REVIEW

**Comment by tpapp** [comment]
Thanks for the fix, and sorry for getting back to you so late. @ExpandingMan, is this covered by #13?

**Comment by jwscook** [comment]
No problem!

**Comment by ExpandingMan** [comment]
I'm also sorry for forgetting about this.  When I made my changes, I originally went the route you did and required the package to be imported, but later realized this was a potential problem and that it should be possible to run this without importing.  This is now possible, so I'm going to close this PR.

Thanks though!  And really sorry I did not respond to this sooner, I saw the message but then forgot.

**Comment by jwscook** [comment]
No problem. I'd forgotten about it too.

**Pull request closed without merging**
